// <auto-generated />
namespace RoutingSample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddDateTime : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206072007200_AddDateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1fVuiXkXmeLVZmPpf1H6XFZZITL67w8f0/Edh4CsY9sl9TpKSHXXr+5XuXc8Wcfvayr2Xra+o2o2e+VXwcf0EfUcJXX7fWr/FxfPZt9lN4N37vbfdG+5r2D3um3ZXtv76P0xboss0lJH5xnZZN/lK4+ffS6rer883yZ11mbz15mbZvXS7ybM/ZKhUerT29HiId3d/ZAiLvZclm1WUvT3EO8g6ZSBX8YfF+3Nc3NR+mz4l0+e54vL9q5xfmL7J35hH79KP1qWRCf0Uttvc79Mcrfm/t+mjfTulgJmj/kvo8vs4KbPyXKm97x+5sClOhNlg/t8V3HXH2WIzlos4KmVHsKeB1f5u+6TCgvvs7bcFJIJFxHIhdjw8VRhGzXTvbuivAZIb07IKWPv8hWK8LSk1r9JH0tInuy/fr9hXIhMO5Om4hsWmxtTyQN2UXe+Za6JkyfFXXT0vxkkwzTcTJb9Jq9D6FNlx16d1WBI795Ab9H5lV1mJ2eDiBHzmc0wgVJNw9Wh0r4DKgnfff1NCuzOqJgTqpyvVgOKalNbwdy74MJvrg9vECWfXjBF7eH15FPH2Lnqz7Mx3c7xO5Oqye/2rKj3Lt8sknWuk1s71bmOrL1WPn8ZjPZY3xp8lFKxLosZmD619dNmy/GaDB+/YvK"
                       + "k7Kg8boGX2TL4jxv2jfV2xwmn+Ty69tZa16aZlb+v9TYFhj9jWZ1o3rvg48YyeVlVk/nWb21yN7deV/jEzF8HwQvasxm9Dv8s2/UmPVV8a0s2SZDJjxN+E4qQl3wdAbwa5q5vog9vuv7q49pCooLBwLe6zKfYkYcUNPmbHleGYrT0HyMTJPOhHyRtxnRPzuu2+I8m7b09TRvGnZtfjIr19TkdDHJZ2fLL9ftat0eN02+mJTX/ngf393cP9vyEOfHXzJPeTrl6w+B0CzAQl8un6yLcmbxfhZhoQEQYBaVQsKKXDsCd3FtIb2olrcEpOR7mq/yJWT4TU42l4A1Xy5fZ5f5MG430zCk2OOnRXZRZ4tGYbj36U9iPwp+jv6fAAAA///Zzr/RcQ0AAA=="; }
        }
    }
}
