// <auto-generated />
namespace RoutingSample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddCategory : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206072017237_AddCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1fVuiXkXmeLVZmPpf1H6XFZZITL67w8f0/Edh4CsY9sl9TpKSHXXr+5XuXc8Wcfvayr2Xra+o2o2e+VXwcf0EfUcJXX7fWr/FxfPZt9lN4N37vbfdG+5r2D3um3ZXtv76P0xboss0lJH5xnZZN/lK4+ffS6rer883yZ11mbz15mbZvXS7ybM/ZKhUerT29HiId3d/ZAiLvZclm1WUvT3EO8g+YJdXxR1dcG2ddtTRPzUfqseJfPnufLi3ZuEf4ie2c+oV8/Sr9aFsRk9FJbr3N/gPL35o51OvDHD73vp3kzrYuV0OeH3PfxZVZw86dEedM7fn9TgBI9LvGhPb7ruLrP6ySAbVYQL2lPgZDhy/xdl/vlxdd5G04KyaLrSARybMQnipDt2gn9XZF6ox3uDqiHx19kqxVh6akL/SR9LbriZPv1+2uDhcC4O20iSsFia3siMcwu8s631DVh+qyom5bmJ5tkmI6T2aLX7H0Ibbrs0Lurgxz5zQv4PTKvqjzt9HQAOXI+oxEuSK3wYHWohM+AXtR3X0+zMqsjmu2kKteL5ZB23PS2Uzg+DPfp7SEFGsQHFnxxe3iBVvDhBV/cHl5H0n2Ina/6MB/f7Uxbl0E8TaAtO/apy3GbpLbbxPZupbcjpY9VYm629D0RkiYf"
                       + "pUSsy2IG8Xl93bT5YowG49e/qDwpCxqva/BFtizO86Z9U73N4bWQhH99V8FayKaZlf8v9RcKjP5Gz2CjoeiD79r55WVWT+dZvbXI3t15XxsWsd0fBC9ijz8IXtTGzuh3+KvfqI3tW4gBvd9hqg32VQSE8J1UhLrg6ezy17S+fXl9fNf33x/TFBQXDgS8+WU+xYw4oKbN2fK8MhSnofkYmSadCfkibzOif3Zct8V5Nm3p62neNOxx/WRWrqnJ6WKSz86WX67b1bo9bpp8MSkDc/D47ub+2cUIcX78JfOUp6C+/hAIzQIs9OXyybooZxbvZxEWGgABZlGRJqzI44RMXltIL6rlLQEp+Z7mq3wJhfAmJ1eAgDVfLl9nl/kwbjfTMKTY46dFdlFni0ZhuPfpT2I/CgaP/p8AAAD//9IaQceBDgAA"; }
        }
    }
}
